import { useCSSVariable } from 'uniwind';

import { ThemeFallbacks } from '@/constants/theme';

function asColor(value: string | number | undefined, fallback: string): string {
  return typeof value === 'string' && value.length > 0 ? value : fallback;
}

/**
 * Resolved semantic colours for APIs that cannot accept Uniwind class names
 * (native icons, maps, SVG charts, navigation chrome, and gradients).
 */
export function useThemeTokens() {
  const values = useCSSVariable([
    '--color-primary',
    '--color-primary-soft',
    '--color-primary-foreground',
    '--color-primary-muted',
    '--color-accent',
    '--color-accent-lilac',
    '--color-accent-peach',
    '--color-accent-lemon',
    '--color-accent-coral',
    '--color-accent-aqua',
    '--color-background',
    '--color-canvas',
    '--color-foreground',
    '--color-muted',
    '--color-muted-strong',
    '--color-inverse',
    '--color-border',
    '--color-border-subtle',
    '--color-border-strong',
    '--color-card',
    '--color-surface-1',
    '--color-surface-2',
    '--color-surface-raised',
    '--color-surface-tray',
    '--color-danger',
    '--color-warning',
    '--color-success',
    '--color-income',
    '--color-expense',
    '--color-transfer',
    '--color-state-pending',
    '--color-state-attention',
    '--color-state-approved',
    '--color-state-destructive',
    '--color-category-food',
    '--color-category-transport',
    '--color-category-shopping',
    '--color-category-home',
    '--color-category-health',
    '--color-category-entertainment',
    '--color-category-income',
    '--color-category-other',
    '--color-chart-1',
    '--color-chart-2',
    '--color-chart-3',
    '--color-chart-4',
    '--color-chart-5',
    '--color-chart-6',
  ]);

  const [
    primary,
    primarySoft,
    primaryForeground,
    primaryMuted,
    accent,
    accentLilac,
    accentPeach,
    accentLemon,
    accentCoral,
    accentAqua,
    background,
    canvas,
    foreground,
    muted,
    mutedStrong,
    inverse,
    border,
    borderSubtle,
    borderStrong,
    card,
    surface1,
    surface2,
    surfaceRaised,
    surfaceTray,
    danger,
    warning,
    success,
    income,
    expense,
    transfer,
    pending,
    attention,
    approved,
    destructive,
    categoryFood,
    categoryTransport,
    categoryShopping,
    categoryHome,
    categoryHealth,
    categoryEntertainment,
    categoryIncome,
    categoryOther,
    chart1,
    chart2,
    chart3,
    chart4,
    chart5,
    chart6,
  ] = values;

  return {
    primary: asColor(primary, ThemeFallbacks.primary),
    primarySoft: asColor(primarySoft, ThemeFallbacks.primarySoft),
    primaryForeground: asColor(primaryForeground, ThemeFallbacks.primaryForeground),
    primaryMuted: asColor(primaryMuted, ThemeFallbacks.primaryMuted),
    accent: asColor(accent, ThemeFallbacks.accent),
    accents: {
      lilac: asColor(accentLilac, ThemeFallbacks.accentLilac),
      peach: asColor(accentPeach, ThemeFallbacks.accentPeach),
      lemon: asColor(accentLemon, ThemeFallbacks.accentLemon),
      coral: asColor(accentCoral, ThemeFallbacks.accentCoral),
      aqua: asColor(accentAqua, ThemeFallbacks.accentAqua),
    },
    background: asColor(background, ThemeFallbacks.background),
    canvas: asColor(canvas, ThemeFallbacks.canvas),
    foreground: asColor(foreground, ThemeFallbacks.foreground),
    muted: asColor(muted, ThemeFallbacks.muted),
    mutedStrong: asColor(mutedStrong, ThemeFallbacks.mutedStrong),
    inverse: asColor(inverse, ThemeFallbacks.inverse),
    border: asColor(border, ThemeFallbacks.border),
    borderSubtle: asColor(borderSubtle, ThemeFallbacks.borderSubtle),
    borderStrong: asColor(borderStrong, ThemeFallbacks.borderStrong),
    card: asColor(card, ThemeFallbacks.card),
    surface1: asColor(surface1, ThemeFallbacks.surface1),
    surface2: asColor(surface2, ThemeFallbacks.surface2),
    surfaceRaised: asColor(surfaceRaised, ThemeFallbacks.surfaceRaised),
    surfaceTray: asColor(surfaceTray, ThemeFallbacks.surfaceTray),
    danger: asColor(danger, ThemeFallbacks.danger),
    warning: asColor(warning, ThemeFallbacks.warning),
    success: asColor(success, ThemeFallbacks.success),
    income: asColor(income, ThemeFallbacks.income),
    expense: asColor(expense, ThemeFallbacks.expense),
    transfer: asColor(transfer, ThemeFallbacks.transfer),
    states: {
      pending: asColor(pending, ThemeFallbacks.pending),
      attention: asColor(attention, ThemeFallbacks.attention),
      approved: asColor(approved, ThemeFallbacks.approved),
      destructive: asColor(destructive, ThemeFallbacks.destructive),
    },
    category: {
      food: asColor(categoryFood, ThemeFallbacks.category.food),
      transport: asColor(categoryTransport, ThemeFallbacks.category.transport),
      shopping: asColor(categoryShopping, ThemeFallbacks.category.shopping),
      home: asColor(categoryHome, ThemeFallbacks.category.home),
      health: asColor(categoryHealth, ThemeFallbacks.category.health),
      entertainment: asColor(categoryEntertainment, ThemeFallbacks.category.entertainment),
      income: asColor(categoryIncome, ThemeFallbacks.category.income),
      other: asColor(categoryOther, ThemeFallbacks.category.other),
    },
    chart: [
      asColor(chart1, ThemeFallbacks.chart[0]),
      asColor(chart2, ThemeFallbacks.chart[1]),
      asColor(chart3, ThemeFallbacks.chart[2]),
      asColor(chart4, ThemeFallbacks.chart[3]),
      asColor(chart5, ThemeFallbacks.chart[4]),
      asColor(chart6, ThemeFallbacks.chart[5]),
    ] as const,
  };
}
